# -*- coding: utf-8 -*-
"""biblesonnet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W_9snihuMX4L3-utRu-kardr0ORtRdRT
"""

#install libraries and methods
!pip install pronouncing
from textblob import TextBlob
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('brown')
import random
import pronouncing
import re

#import bible.txt to file
with open('/content/drive/MyDrive/creativecoding/bible.txt') as txt:
  BibleBook = txt.read()

#reformat and make file a blob, label each word with POS tags
BibleBook = BibleBook.replace("“","\"").replace("”","")
blob = TextBlob(BibleBook)
tagged_words = blob.tags
blob = re.sub(r'[,\.\"“”\?\!\;\-]', ' ', str(blob)).replace('’','\'')

#initialize wordlist list, splits blob by spaces between words, adds each word to wordlist
wordlist = []
blob = blob.split(" ")
for word in blob:
  wordlist.append(word)
#code from https://stackoverflow.com/questions/43301841/remove-n-from-a-list, removes python line spacing commands and moves reformated list to wordlist2
wordlist2 = [x.replace('\n', '').replace(' ', ' ') for x in wordlist]

#initialize wordlist3, adds words from blob to list if word has a pronunciation from pronouncing
wordlist3 = []
for word in wordlist2:
  stresswordphonemes = pronouncing.phones_for_word(word)
  if (len(stresswordphonemes) > 0):
    wordlist3.append(word)

#initialize wordlist4, adds words from wordlist3 if word is an iamb (one unstressed syllable followed by one stressed syllable)
wordlist4 = []
for i in wordlist3:
    stresswordphonemes2 = pronouncing.phones_for_word(i)
    if (len(stresswordphonemes2) > 0):
      if ("0" in stresswordphonemes2[0] and "1" in stresswordphonemes2[0] and stresswordphonemes2[0].index('0') < stresswordphonemes2[0].index('1') 
      and stresswordphonemes2[0].count('0') < 2 and stresswordphonemes2[0].count('1') < 2 and "2" not in stresswordphonemes2[0]):
        wordlist4.append(i)
 
#reformats and standardizes each element in wordlist4, resulting in new blob "iambblob" comprising each iamb from text file
#code from https://stackoverflow.com/questions/3840843/how-to-downcase-the-first-character-of-a-string
func = lambda s: s[:1].lower() + s[1:] if s else ''
lowerwordlist4 = []
for s in wordlist4:
  if s[0].isupper():
    lowerwordlist4.append(func(s))
  else:
    lowerwordlist4.append(s)
uniqueiambs = list(set(lowerwordlist4))
text = " "
newtext = (text.join(uniqueiambs))
iambblob = TextBlob(newtext)

#poem construction, rhymes last word in line 1 with last word in line 2 and rhymes last word in line 3 with last word in line 4, randomly choses from
#different words in POS lists for sensability and legibility of poem
nouns = []
proper_nouns = []
pronouns = []
adjectives = []
determiners = []
adverbs = []
verbs = []
prepositions = []
for w,pos in tagged_words:
  if (pos == 'JJ' or pos == 'JJR' or pos == 'JJS' and len(w) > 2):
    adjectives.append(w)
  if (pos == 'NN' or pos == 'NNS' or pos == 'POS' and len(w) > 2):
    nouns.append(w)
  if (pos == 'NNP' or pos == 'NNPS' and len(w) > 2):
    w.capitalize()
    proper_nouns.append(w)
  if (pos == 'RB' or pos == 'RBR' or pos == 'RBS' or pos == 'WRB' and len(w) > 2):
    adverbs.append(w)
  if (pos == 'IN'):
    prepositions.append(w)
  if (pos == 'VB' or pos == 'VBD' or pos == 'VBG' or pos == 'VBN' or pos == 'VBP' or pos == 'VBZ' and len(w) > 2):
    verbs.append(w)
  if (pos == 'PRP' or pos == 'PRP$' or pos == 'WP' or pos == 'WP$' and len(w) > 2):
    pronouns.append(w)
  if (pos == 'DT' or pos == 'PDT' or pos == 'WDT' and len(w) > 2):
    determiners.append(w)
line1word1 = random.choice(nouns)
line1word2 = random.choice(adverbs)
line1word3 = random.choice(verbs)
line1word4 = random.choice(adverbs)
line1word5 = random.choice(verbs)
line2word1 = random.choice(adjectives)
line2word2 = random.choice(pronouns)
line2word3 = random.choice(adverbs)
line2word4 = random.choice(nouns)
line2word5 = random.choice(verbs)
line3word1 = random.choice(adjectives) or random.choice(adverbs)
line3word2 = random.choice(nouns) or random.choice(pronouns)
line3word3 = random.choice(prepositions) or random.choice(adverbs)
line3word4 = random.choice(adverbs) or random.choice(adjectives)
line3word5 = random.choice(verbs)
line4word1 = random.choice(adjectives)
line4word2 = random.choice(pronouns)
line4word3 = random.choice(prepositions)
line4word4 = random.choice(adjectives)
line4word5 = random.choice(nouns)

line5word1 = random.choice(nouns)
line5word2 = random.choice(adverbs)
line5word3 = random.choice(verbs)
line5word4 = random.choice(adverbs)
line5word5 = random.choice(verbs)
line6word1 = random.choice(adjectives)
line6word2 = random.choice(pronouns)
line6word3 = random.choice(adverbs)
line6word4 = random.choice(nouns)
line6word5 = random.choice(verbs)
line7word1 = random.choice(adjectives) or random.choice(adverbs)
line7word2 = random.choice(nouns) or random.choice(pronouns)
line7word3 = random.choice(prepositions) or random.choice(adverbs)
line7word4 = random.choice(adverbs) or random.choice(adjectives)
line7word5 = random.choice(verbs)
line8word1 = random.choice(adjectives)
line8word2 = random.choice(pronouns)
line8word3 = random.choice(prepositions)
line8word4 = random.choice(adjectives)
line8word5 = random.choice(nouns)

line9word1 = random.choice(adjectives) or random.choice(adverbs)
line9word2 = random.choice(nouns) or random.choice(pronouns)
line9word3 = random.choice(prepositions) or random.choice(adverbs)
line9word4 = random.choice(adverbs) or random.choice(adjectives)
line9word5 = random.choice(verbs)
line10word1 = random.choice(adjectives)
line10word2 = random.choice(pronouns)
line10word3 = random.choice(prepositions)
line10word4 = random.choice(adjectives)
line10word5 = random.choice(nouns)
line11word1 = random.choice(nouns)
line11word2 = random.choice(adverbs)
line11word3 = random.choice(verbs)
line11word4 = random.choice(adverbs)
line11word5 = random.choice(verbs)
line12word1 = random.choice(adjectives)
line12word2 = random.choice(pronouns)
line12word3 = random.choice(adverbs)
line12word4 = random.choice(nouns)
line12word5 = random.choice(verbs)
line13word1 = random.choice(adjectives) or random.choice(adverbs)
line13word2 = random.choice(nouns) or random.choice(pronouns)
line13word3 = random.choice(prepositions) or random.choice(adverbs)
line13word4 = random.choice(adverbs) or random.choice(adjectives)
line13word5 = random.choice(verbs)
line14word1 = random.choice(adjectives)
line14word2 = random.choice(pronouns)
line14word3 = random.choice(prepositions)
line14word4 = random.choice(adjectives)
line14word5 = random.choice(nouns)


line1_rhymes = []
for w,pos in tagged_words:
  if (pos == 'VB' or pos == 'VBD' or pos == 'VBG' or pos == 'VBN' or pos == 'VBP' or pos == 'VBZ' or pos == 'PRP' 
      or pos == 'PRP$' or pos == 'WP' or pos == 'NN' or pos == 'RB' or pos == 'RBR' or pos == 'RBS'):
    if (w in pronouncing.rhymes(line1word5)):
      line1_rhymes.append(w)

line2_rhymes = []
for w,pos in tagged_words:
  if (pos == 'VB' or pos == 'VBD' or pos == 'VBG' or pos == 'VBN' or pos == 'VBP' or pos == 'VBZ' or pos == 'PRP' 
      or pos == 'PRP$' or pos == 'WP' or pos == 'NN' or pos == 'RB' or pos == 'RBR' or pos == 'RBS'):
    if (w in pronouncing.rhymes(line2word5)):
      line2_rhymes.append(w)


line9_rhymes = []
for w,pos in tagged_words:
  if (pos == 'VB' or pos == 'VBD' or pos == 'VBG' or pos == 'VBN' or pos == 'VBP' or pos == 'VBZ' or pos == 'PRP' 
      or pos == 'PRP$' or pos == 'WP' or pos == 'NN' or pos == 'RB' or pos == 'RBR' or pos == 'RBS'):
    if (w in pronouncing.rhymes(line9word5)):
      line9_rhymes.append(w)


line10_rhymes = []
for w,pos in tagged_words:
  if (pos == 'VB' or pos == 'VBD' or pos == 'VBG' or pos == 'VBN' or pos == 'VBP' or pos == 'VBZ' or pos == 'PRP' 
      or pos == 'PRP$' or pos == 'WP' or pos == 'NN' or pos == 'RB' or pos == 'RBR' or pos == 'RBS'):
    if (w in pronouncing.rhymes(line10word5)):
      line10_rhymes.append(w)


line11_rhymes = []
for w,pos in tagged_words:
  if (pos == 'VB' or pos == 'VBD' or pos == 'VBG' or pos == 'VBN' or pos == 'VBP' or pos == 'VBZ' or pos == 'PRP' 
      or pos == 'PRP$' or pos == 'WP' or pos == 'NN' or pos == 'RB' or pos == 'RBR' or pos == 'RBS'):
    if (w in pronouncing.rhymes(line11word5)):
      line11_rhymes.append(w)

poemline1 =  line1word1.capitalize() + " " + line1word2 + " " + line1word3 + " " + line1word4 + " " + line1word5
print(poemline1)
poemline2 = line2word1.capitalize() + " " + line2word2 + " " + line2word3 + " " + line2word4 + " " + line2word5
print(poemline2)
if (len(line2_rhymes) > 0):
  poemline3 = line3word1.capitalize() + " " + line3word2 + " " + line3word3 + " " + line3word4 + " " + random.choice(line2_rhymes)
else:
  poemline3 = line3word1.capitalize() + " " + line3word2 + " " + line3word3 + " " + line3word4 + " " + line3word5
print(poemline3)
if (len(line1_rhymes) > 0):
  poemline4 = line4word1.capitalize() + " " + line4word2 + " " + line4word3 + " " + line4word4 + " " + random.choice(line1_rhymes)
else:
  poemline4 = line4word1.capitalize() + " " + line4word2 + " " + line4word3 + " " + line4word4 + " " + line4word5
print(poemline4)

if (len(line1_rhymes) > 0):
  poemline5 =  line5word1.capitalize() + " " + line5word2 + " " + line5word3 + " " + line5word4 + " " + random.choice(line1_rhymes)
else:
  poemline5 =  line5word1.capitalize() + " " + line5word2 + " " + line5word3 + " " + line5word4 + " " + line5word5
print(poemline5)
if (len(line2_rhymes) > 0):
  poemline6 = line6word1.capitalize() + " " + line6word2 + " " + line6word3 + " " + line6word4 + " " + random.choice(line2_rhymes)
else:
  poemline6 = line6word1.capitalize() + " " + line6word2 + " " + line6word3 + " " + line6word4 + " " + line6word5
print(poemline6)
if (len(line2_rhymes) > 0):
  poemline7 = line7word1.capitalize() + " " + line7word2 + " " + line7word3 + " " + line7word4 + " " + random.choice(line2_rhymes)
else:
  poemline7 = line7word1.capitalize() + " " + line7word2 + " " + line7word3 + " " + line7word4 + " " + line7word5
print(poemline7)
if (len(line1_rhymes) > 0):
  poemline8 = line8word1.capitalize() + " " + line8word2 + " " + line8word3 + " " + line8word4 + " " + random.choice(line1_rhymes) + "."
else:
  poemline8 = line8word1.capitalize() + " " + line8word2 + " " + line8word3 + " " + line8word4 + " " + line8word5 + "."
print(poemline8)
print("\n")

poemline9 = line9word1.capitalize() + " " + line9word2 + " " + line9word3 + " " + line9word4 + " " + line9word5
print(poemline9)
poemline10 = line10word1.capitalize() + " " + line10word2 + " " + line10word3 + " " + line10word4 + " " + line10word5
print(poemline10)
poemline11 =  line11word1.capitalize() + " " + line11word2 + " " + line11word3 + " " + line11word4 + " " + line11word5
print(poemline11)
if (len(line9_rhymes) > 0):
  poemline12 = line12word1.capitalize() + " " + line12word2 + " " + line12word3 + " " + line12word4 + " " + random.choice(line9_rhymes)
else:
  poemline12 = line12word1.capitalize() + " " + line12word2 + " " + line12word3 + " " + line12word4 + " " + line12word5
print(poemline12)
if (len(line10_rhymes) > 0):
  poemline13 = line13word1.capitalize() + " " + line13word2 + " " + line13word3 + " " + line13word4 + " " + random.choice(line10_rhymes)
else:
  poemline13 = line13word1.capitalize() + " " + line13word2 + " " + line13word3 + " " + line13word4 + " " + line13word5
print(poemline13)
if (len(line11_rhymes) > 0):
  poemline14 = line14word1.capitalize() + " " + line14word2 + " " + line14word3 + " " + line14word4 + " " + random.choice(line11_rhymes) + "."
else:
  poemline14 = line14word1.capitalize() + " " + line14word2 + " " + line14word3 + " " + line14word4 + " " + line14word5 + "."
print(poemline14)